# Development Profile
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
logging.level.com.urlshortener=DEBUG
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=ERROR